/*
 * settings_factory.c
 *
 *  Created on: 16 Aug 2023
 *      Author: ben
 */

#include "settings_factory.h"

static const settings_t settings_factory = {
  .pcs = {
     {
       .mode = PC_MODE_ON,
       .chan = 0,
       .pc = 0,
       .name = "Default PC0",
     },
     {
       .mode = PC_MODE_ON,
       .chan = 0,
       .pc = 1,
       .name = "Default PC1",
     },
     {
       .mode = PC_MODE_ON,
       .chan = 0,
       .pc = 2,
       .name = "Default PC2",
     },
     {
       .mode = PC_MODE_ON,
       .chan = 0,
       .pc = 3,
       .name = "Default PC3",
     },
     {
       .mode = PC_MODE_ON,
       .chan = 0,
       .pc = 4,
       .name = "Default PC4",
     },
  },
  .ias = {
      // IA 0-7
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_LATCH,
        .midi_chan = 10,
        .midi_data0 = 80,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '0', '0', 0},
      },
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_TOGGLE,
        .midi_chan = 10,
        .midi_data0 = 81,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '0', '1', 0},
      },
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_LATCH,
        .midi_chan = 10,
        .midi_data0 = 82,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '0', '2', 0},
      },
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_LATCH,
        .midi_chan = 10,
        .midi_data0 = 83,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '0', '3', 0},
      },
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_LATCH,
        .midi_chan = 10,
        .midi_data0 = 84,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '0', '4', 0},
      },
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_LATCH,
        .midi_chan = 10,
        .midi_data0 = 85,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '0', '5', 0},
      },
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_LATCH,
        .midi_chan = 10,
        .midi_data0 = 86,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '0', '6', 0},
      },
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_LATCH,
        .midi_chan = 10,
        .midi_data0 = 87,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '0', '7', 0},
      },
      // IA 8-15
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_LATCH,
        .midi_chan = 10,
        .midi_data0 = 88,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '0', '8', 0},
      },
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_TOGGLE,
        .midi_chan = 10,
        .midi_data0 = 89,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '0', '9', 0},
      },
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_LATCH,
        .midi_chan = 10,
        .midi_data0 = 90,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '1', '0', 0},
      },
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_LATCH,
        .midi_chan = 10,
        .midi_data0 = 91,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '1', '1', 0},
      },
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_LATCH,
        .midi_chan = 10,
        .midi_data0 = 92,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '1', '2', 0},
      },
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_LATCH,
        .midi_chan = 10,
        .midi_data0 = 93,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '1', '3', 0},
      },
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_LATCH,
        .midi_chan = 10,
        .midi_data0 = 94,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '1', '4', 0},
      },
      {
        .type = IA_TYPE_CC,
        .mode = IA_MODE_LATCH,
        .midi_chan = 10,
        .midi_data0 = 95,
        .midi_data1 = 0x7F,
        .midi_data2 = 0,
        .id = {'I', 'A', '1', '5', 0},
      },
      // IA 8-15
      {
       .type = IA_TYPE_CC,
       .mode = IA_MODE_LATCH,
       .midi_chan = 10,
       .midi_data0 = 96,
       .midi_data1 = 0x7F,
       .midi_data2 = 0,
       .id = {'I', 'A', '1', '6', 0},
      },
      {
       .type = IA_TYPE_CC,
       .mode = IA_MODE_TOGGLE,
       .midi_chan = 10,
       .midi_data0 = 97,
       .midi_data1 = 0x7F,
       .midi_data2 = 0,
       .id = {'I', 'A', '1', '7', 0},
      },
      {
       .type = IA_TYPE_CC,
       .mode = IA_MODE_LATCH,
       .midi_chan = 10,
       .midi_data0 = 98,
       .midi_data1 = 0x7F,
       .midi_data2 = 0,
       .id = {'I', 'A', '1', '8', 0},
      },
      {
       .type = IA_TYPE_CC,
       .mode = IA_MODE_LATCH,
       .midi_chan = 10,
       .midi_data0 = 99,
       .midi_data1 = 0x7F,
       .midi_data2 = 0,
       .id = {'I', 'A', '1', '9', 0},
      },
      {
       .type = IA_TYPE_CC,
       .mode = IA_MODE_LATCH,
       .midi_chan = 10,
       .midi_data0 = 100,
       .midi_data1 = 0x7F,
       .midi_data2 = 0,
       .id = {'I', 'A', '2', '0', 0},
      },
      {
       .type = IA_TYPE_CC,
       .mode = IA_MODE_LATCH,
       .midi_chan = 10,
       .midi_data0 = 101,
       .midi_data1 = 0x7F,
       .midi_data2 = 0,
       .id = {'I', 'A', '2', '1', 0},
      },
      {
       .type = IA_TYPE_CC,
       .mode = IA_MODE_LATCH,
       .midi_chan = 10,
       .midi_data0 = 102,
       .midi_data1 = 0x7F,
       .midi_data2 = 0,
       .id = {'I', 'A', '2', '2', 0},
      },
      {
       .type = IA_TYPE_CC,
       .mode = IA_MODE_LATCH,
       .midi_chan = 10,
       .midi_data0 = 103,
       .midi_data1 = 0x7F,
       .midi_data2 = 0,
       .id = {'I', 'A', '2', '3', 0},
      },
  }
};

const settings_t* get_settings_factory() {
  return &settings_factory;
}
